### ISSUE TITLE
Auslesen Antwortnachricht

### ISSUE THREAD

**Issue by DanielNe** [blaulichtSMS/docs#1]
Mir wurde gesagt, dass mit dem Update nun auch die Antworten der Mitglieder ausgelesen werden können. Gibt es dafür ein Beispiel?

Vielen Dank!

LG

**Comment by pmig** [comment]
Hallo @DanielNe ,

Ich gehe davon aus, dass du dich auf die Dashboard API für deine Feuerwehr beziehst?

Die Antwortnachricht (`participationMessage`) ist Teil des `AlarmRecipients`, wie in der [Dasboard API > AlarmRecipient](https://github.com/blaulichtSMS/docs/blob/master/dashboard_api_v1.md#alarmrecipient) beschrieben.

Folgender Beispiel Html und Javascript Code listet alle Alarmteilnehmer der letzten Alarme mit ihrem Status und ihrer Antwortnachricht auf:

**index.html:**
```
<script type="text/javascript">
	// FILL IN THE  SESSION ID BELOW
	var SESSION_ID = ''; // received after login


	var dashboardUrl = 'https://api.blaulichtsms.net/blaulicht/api/alarm/v1/dashboard/' + SESSION_ID;


	var displayParticipationMessage = function(dashboardJSON) {
		var dashboard = JSON.parse(dashboardJSON);

		dashboard.alarms.forEach(function(alarm) {
			alarm.recipients.forEach(function (recipient) {
				document.write(recipient.name + ' ' + recipient.participation + ' ' + recipient.participationMessage + '<br>');
			});
			document.write('<hr>');
		});
	};


	var loadDashboard = function(url, callback) {
	    var xmlHttp = new XMLHttpRequest();
	    xmlHttp.onreadystatechange = function() { 
	        if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
	            callback(xmlHttp.responseText);
	    }
	    xmlHttp.open("GET", url, true); // true for asynchronous 
	    xmlHttp.send(null);
	};


	loadDashboard(dashboardUrl, displayParticipationMessage);
</script>
```

Du musst nur noch deine Session ID hinterlegen.

Beachte bitte, dass das HTML file von einem Webserver (apache, nginx etc.) ausgeliefert werden muss, damit der Request auf die Blaulicht API klappt

Ich hoffe, dass ich dir helfen konnte.

**Comment by pmig** [comment]
Hallo @DanielNe ,

Ich habe nun zu dem [Javascript Beispiel ](https://github.com/blaulichtSMS/docs/blob/master/examples/dashboard-api/javascript/dashboard-api-example.html) auch ein PHP Beispiel für den [Login](https://github.com/blaulichtSMS/docs/blob/master/examples/dashboard-api/php/dasboard-api-login-example.php) und den [Dashboard Request](https://github.com/blaulichtSMS/docs/blob/master/examples/dashboard-api/php/dasboard-api-dasboard-example.php) hinzugefügt.

**Comment by DanielNe** [comment]
Vielen Dank!. 
Leider hat das noch nicht so funktioniert, bekomme keine Daten. 
Wenn ich den API Link + Session in den Browser eingebe bekomme ich aber die Daten. 
Oder funktioniert das nur bei Einsätzen und nicht bei infos?

Schön wäre ein "Demo Bereich" wo man alarme für tests anlegen könnte.

Vielen Dank!

**Comment by DanielNe** [comment]
Frage hat sich selbst beantwortet. 
Für Andere:
```
Auslesen Alarme:
dashboard.alarms.forEach
Auslesen Infos:
dashboard.infos.forEach
```

**Comment by pmig** [comment]
@DanielNe wir können dir natürlich einen kostenfreien serperaten Testzugang zur Verfügung stellen, damit du Testalarme versenden kannst, falls du daran Interesse hast, melde dich bitte ein unserem [Kundensupport](https://start2.blaulichtsms.net/de/contact)

**Comment by DanielNe** [comment]
Vielen Dank für den Support!
