### ISSUE TITLE
Einsatzlistener

### ISSUE THREAD

**Issue by strudelbeast** [blaulichtSMS/docs#10]
Hallo,
Meine Feuerwehr ist gerade dabei den Einsatzmonitor zu installieren und ich arbeite an einem Alamierungs-/Heimsteuerungssystem via Skript auf dem Raspberry Pi.
Ich hätte gerne gewusst wie man das am besten macht das man alle 5 Sekunden abfragt ob es einen neuen Einsatz gibt und ob das ohne Logindaten möglich ist oder ob ich mir da welche besorgen müsste.

**Comment by pmig** [comment]
Hallo @strudelbeast ,

Um die neuesten Alarme abzugreifen, brauchst du den Einsatzmonitorbox Zugangsdaten. 

Am Besten legt euer Administrator für dein Skript einen eigenen Einsatzmonitor Benutzer an.

Mit diesen Kannst du dann den Login Token generieren, mit dem du dann die neusten Einsätze der über die Dashboard API bekommst.

Ohne Zugangsdaten ist das nicht möglich.
