### ISSUE TITLE
Mehrere Sessions

### ISSUE THREAD

**Issue by noxish** [blaulichtSMS/docs#12]
Hallo 
ich würde gerne mehrere einsatzmonitore gleichzeitig laufen lassen ist das irgendwie möglich`?
bspw mit der sessionid?

ich habe derzeit zwei einsatzmonitore angelegt und diese möchte ich in einem Browser Wechseln lassen daher die frage.

**Comment by pmig** [comment]
Hallo @noxish ,

Du kannst Dir in der Webplattform mehrere Einsatzmonitore anlegen. Für die kannst du dich dann am Besten parallel einloggen. Zusätzlich hast du den Vorteil, dass du auf jedem Monitor verschiedene Einstellungen setzen kannst!

Grüße, Philip

**Comment by noxish** [comment]
Hallo @pmig 

das hab ich eh gemacht aber leider hat er mich dann bei beiden Tabs auf der selben Session eingeloggt 
ich schaus mir aber heute nochmals an,

aber Prinzipiell sollte es in dem Fall Funktionieren
Danke ! 👍

**Comment by pmig** [comment]
Hallo,
Ja man müsste für jeden Einsatzmonitor einen anderen Browser / ein anderes Gerät verwenden. Mehrere Tabs in einem Browser teilen sich die Token.

Grüße, Philip

**Comment by domdorn** [comment]
@noxish alternativ kannst du's auch mit "Incognito"-Fenstern probieren, falls du nur einen Browser zur Verfuegung hast. 

lG, Dominik

**Comment by noxish** [comment]
@domdorn danke für den Hinweis meistens liegt die lösung eh vor den füßen :) 
ich werds mal versuchen :)

**Comment by ximex** [comment]
@noxish firefox unterstützt ja "container". Jeder container ist isoliert. Also könntest du dich auch so mit mehreren sessions einloggen in einem browser fenster
