### ISSUE TITLE
Dashboard PHP

### ISSUE THREAD

**Issue by 19flashover69** [blaulichtSMS/docs#2]
Hallo!

Hat sich jemand schon mit PHP und dem Dashboard beschäftigt?
Möchte gerne ein wenig herumtesten aber irgendwie bekomme ich die Verbindung nicht hin.
Hat schon jemand eine Beispiel Datei?
Wie kommt ihr zur Session ID?

Lg

**Comment by pmig** [comment]
Hallo @19flashover69 ,

Die Session ID erhälst du nach einem erfolgreichen Login.

Ich habe nun ein PHP Beispiel für den [Login](https://github.com/blaulichtSMS/docs/blob/master/examples/dashboard-api/php/dasboard-api-login-example.php) und den [Dashboard Request](https://github.com/blaulichtSMS/docs/blob/master/examples/dashboard-api/php/dasboard-api-dasboard-example.php) hinzugefügt.

Bei weiteren Fragen, melde dich jederzeit.

**Comment by 19flashover69** [comment]
Dankeschön - erhalte noch keine Antwort vom Script.. Muss irgendetwas besonderes Installiert sein? Ist die Version PHP 5.4.5 zu nieder?

Lg

**Comment by pmig** [comment]
Welches Script führst du aus?
Hast du die deine einsatzmonitorzugangsdaten eingetragen?

Ja es wird die PHP curl extension benötigt. Kannst du via php_info() sicherstellen, dass du sie installiert hast?

**Comment by 19flashover69** [comment]
Das normale Login Script - Ja Daten hab ich erhalten

Schaut nicht so aus - http://www.ff-stgeorgen.at/blaulichtsms.php 5.4
Bzw. http://dev.ff-stgeorgen.at/blaulichtsms.php - PHP 7

Lg

**Comment by pmig** [comment]
Dank für deine info, curl scheint installiert zu sein, ich habe das script soeben ausprobiert, und es war tatsächlich ein Fehler im Script. Habe diesen nun ausgbessert.

In Zeile 18 Muss natürlich LOGIN_URL stehen und nicht DASHBOARD_URL [siehe commit](https://github.com/blaulichtSMS/docs/commit/09c435b440b7a4bb5fb676e54b5859ee9ac305a1)

**Comment by 19flashover69** [comment]
Ok Danke - jetzt funktionierts (zumindest die Abfrage) - Bekomme nur 

"{"success":false,"sessionId":null,"error":"INVALID_CREDENTIALS"}" retour.

const CUSTOMER_ID = 'K102xXxxXxx';
const USERNAME = 'FF St. Pölten-St.Georgen';
const PASSWORD = 'xxXxxXxx';

Kundennummer, Benutzername und Passwort

Lg

**Comment by DanielNe** [comment]
Hallo, 
ich denke du verwendest den Falschen Login.
Das ist nicht der Selbe wie zum Intern Bereich sondern den, den du beim Dashboard verwendest.

Des Weiteren verwende ich die CUSTOMER_ID ohne "K" -> nur die Nummer

Vielleicht hilft dir das.

LG

**Comment by 19flashover69** [comment]
Dankesehr hab ich auch ohne versucht – Muss mal bei BlaulichtSMS nachfragen – Ich glaube die Daten stimmen nicht – hab die Daten des Dashboardes versucht und die erhaltenen

Lg

**Comment by DanielNe** [comment]
Versuch dich mit deinen Daten unter http://dashboard.blaulichtsms.net anzumelden.
Das sind die Gleichen wie fürs API. (so hat es bei mir funktioniert)

zB lautet bei mir der Username: "einsatzmonitor"
LG

**Comment by pmig** [comment]
Hallo @19flashover69 , 

Genau wie @DanielNe beschrieben hat, ist die customerId  deine Kundenummer ohne K, der username ist `einsatzmonitor` und das Passwort haben wir dir ursprünglich mit deinen Zugangsdaten gesendet.

Falls es immer noch nicht klappt, wende dich bitte an unseren [Kundensupport](https://start2.blaulichtsms.net/de/contact)!

**Comment by 19flashover69** [comment]
Dankesehr! Jetzt hab ich das Problem gefunden - Die Zugangsdaten warn nicht mehr korrekt.

Sprich jetzt muss ich ein Script erstellen, welches den Status z.B.: alle 5 Minuten aktualisiert und die Session ID extern abspeichert ist das richtig?

Lg

**Comment by pmig** [comment]
Sobald du eine gültige SessionID generiert hast, kannst du diese SessionID in das [Dashboard-Skript](https://github.com/blaulichtSMS/docs/blob/master/examples/dashboard-api/php/dasboard-api-dasboard-example.php#L6) eintragen. Die SessionID wird sich nicht ändern und erst bei weiteren Logins invalidiert.

Dieses Skript sollte dann z.B. jede Minute aktualisiert werden, um die aktuellsten Arlame zu erhalten.

**Comment by 19flashover69** [comment]
Danke funktioniert! Super!

Gibt es auch eine Möglichkeit, nur die Alarmteilnehmer anzuzeigen, die mit yes geantwortet haben?

Lg

**Comment by DanielNe** [comment]
Einfach in der Schleife eine Abfrage mit "yes" erstellen,

Lg

**Comment by 19flashover69** [comment]
Kann mir hier jemand ein Beispiel posten?

PHP versteh ich so halbwegs aber das mit den JSON da steh ich ein wenig an - z.b.: die Audio URL einpflegen ist kein Problem aber z.b.: bei den Geo Daten erhalte ich nur eine weiße seite zurück.

Lg

**Comment by pmig** [comment]
Hallo @19flashover69 ,

Bitte beachte, dass Geo Daten auch `null` sein können, wenn uns diese von der Leitstelle / Alarmgeber nicht übermittelt werden.

Beste Grüße, Philip

**Comment by 19flashover69** [comment]
Ok Dankesehr - Besteht die Möglichkeit mir zu helfen, die Daten mittels Cronejob alle Minuten auszulesen und in eine MySQL Datenbank abzuspeichern?

Lg

**Comment by pmig** [comment]
Für allgemeine Anfragen zur Programmierung von PHP / Mysql Anwendungen kann ich dir [Stackoverflow](https://stackoverflow.com/) ans Herz legen!

Falls du ein spezifisches Problem hast, helfen wir dir hier auch gerne jederzeit.

Ich schließe nun dieses Issue, da die ursprüngliche Frage bereits beantwortet wurde. Falls du ein weiteres Problem hast, erstelle einfach ein neues Issue mit deinem konkreten Problem, damit man dir einfacher helfen kann!

Viel Erfolg mit der Implementierung deines Dashboards!
