### ISSUE TITLE
Printout

### ISSUE THREAD

**Issue by HarryTheBullet** [blaulichtSMS/docs#23]
Liebes Blaulicht SMS Team,
ich habe jetzt bei uns in der Feuerwehr die Administration des Einsatzmonitors übernommen.
Leider haben wir aktuell das Problem, dass wir keine Printouts zu Einsätzen bekommen.

#autoprint

Was muss ich beachten, damit dies einwandfrei funktioniert?
Ich hoffe ich habe mich richtig ausgedrückt.
Danke
Schönen Tag
Harald WEISS
FF-Viehofen

**Comment by stefblsms** [comment]
Sehr geehrter herr Weiss,

meinen Sie einen Ausdruck auf einem Drucker?
Diese Funktion gibt es leider nicht.

Sie können natürlich jederzeit einen Screenshot machen und diesen drucken.

Bitte am Besten immer ein Mail an support@blaulichtsms.net schreiben statt hier ein Ticket.
