### ISSUE TITLE
Alarm Zeitversetzt

### ISSUE THREAD

**Issue by ffmarco122** [blaulichtSMS/docs#3]
Hallo wie kann ich den Alarm/Info Zeitversetzt senden.
'alarmDate'  => '2017-01-26T17:30:21.345Z',
funktioniert leider nicht. 

In der Beschreibung habe ich leider auch nichts gefunden.

lg marco

**Comment by pmig** [comment]
Hallo Marco,

Wir unterstützen natürlich auch zukünftige / zeitversetzte Alarme.

Das Attribute hierfür heißt `startDate`:

`'startDate' => '2017-01-26T17:30:21.345Z',`

Ich erweitere gleich unsere Dokumentation, danke für das Feedback!
