### ISSUE TITLE
Fehlerhaftes Test Basis

### ISSUE THREAD

**Issue by ffmarco122** [blaulichtSMS/docs#4]
Hallo
Damit ich nicht jedes mal ein SMS sende aber auch gewissen Rückmeldungen bekomme und dies auswerten kann, wollte ich die 
TEST BASIS URL verwenden
const TRIGGER_URL =  'https://blaulicht-dev.alpspay.com/blaulicht/api/alarm/v1/trigger';

Ergebnis:
{"result":"INVALID_CUSTOMER_ID","description":"invalid customer id","alarmId":null,"customerId":null,"alarmData":null}

**Comment by pmig** [comment]
Hallo Marco,

Deine blaulichtSMS Organisiation ist nicht automatisch in unserem Testsystem hinterlegt. Daher klappt der Login nicht

Wozu benötigst du den Testzugang genau?

Grüße, Philip

**Comment by ffmarco122** [comment]
Hallo 
Zum Testen der Applikationen ohne dass ich jedesmal eine sms versenden muss und meine Organisation die kosten dafür tragen muss.

lg marco

**Comment by pmig** [comment]
Hallo Marco,

Melde dich bitte zu diese Thema bei unserem [Support](https://start2.blaulichtsms.net/de/contact). Dieser wird sicher eine Lösung mit dir finden, dass du für das Testen der Applikation keine Kosten tragen musst.

Liebe Grüße, Philip
