### ISSUE TITLE
Automatischen Alarm editieren 

### ISSUE THREAD

**Issue by DanielNe** [blaulichtSMS/docs#5]
Gibt es die Möglichkeit automatisch generierte Alarme (zB ausgelöst von der Leitstelle) zu editieren bzw. zu erweitern?

Ein Beispiel wäre dem Alarm GPS Koordinaten hinzuzufügen.

LG

**Comment by pmig** [comment]
Hallo Daniel,

Wir arbeiten gerade intern an einem Service, dass automatisch die Adresse aus einem Alarm ausliest und GPS Koordinaten hinzufügt.

Hierzu bitte ich noch um ein wenig Geduld. 

Edit: Aktuell ist keine API geplant, die das Editieren von automatischen Alarmen vorsieht.

**Comment by DanielNe** [comment]
Vielen Dank, Doch bekommt ihr die gleiche Menge an Daten, als die wir per Fax zugesendet bekommen?

**Comment by pmig** [comment]
Hi @DanielNe, nein wir haben nur den Alarmtext, den wir direkt weiter übermitteln.
Welche Informationen bekommt ihr zusätzlich per Fax?

**Comment by pmig** [comment]
Ich schließe dieses Issue, da wir das Editieren / Erweitern von automatischen Alarmen von Dritten nicht vorgesehen haben.
