### ISSUE TITLE
Message bei Alarm

### ISSUE THREAD

**Issue by stg93** [blaulichtSMS/docs#6]
Hallo,

ich setze gerade den Einsatzmonitor um. Dazu lasse ich einfach die Webapplikation auf einem Raspberry Pi laufen, welcher per HDMI mit einem Fernseher verbunden ist. Den Fernseher möchte ich sobald ein Alarm eintrifft per HDMI CEC einschalten und nach einer gewissen Zeit wieder ausschalten. Gibt es eine saubere Lösung eine Message an den Raspberry zu schicken, sobald ein Alarm eintrifft? (z.B. per Websocket)

Zwei unsaubere Lösungen welche mir eingefallen sind wären:

- alle z.B. 60 Sekunden einen Request zu senden und schauen ob ein Alarm eingetreten ist (busy waitung -> nicht so gut)

- einen Listener auf Änderungen des HTML setzen (instabil bei Änderungen der Implementierung!; auf welche Änderung genau hören?)

LG

**Comment by pmig** [comment]
Hallo,

Ich empfehle dir ganz klar dein Projekt mit _busy waiting / polling_ zu realiseren. Du kannst hierfür am Besten die [Dashboard API](https://github.com/blaulichtSMS/docs/blob/master/dashboard_api_v1.md) mit einem eigenen User verwenden und unsere API z.B. alle 5 Sekunden abfragen.

Meiner Meinung nach ist _busy waiting / polling_ keine unsaubere Lösung, da diese wesentlich skalierbarer und sicherer ist. (Ein Websocket kann abbrechen bei Internetausfall und ist schwer offen zu halten bei vielen gleichzeitigen Verbindungen.)

Andere Projekte haben sich auch eine ähnliche Frage gestellt, falls dich mehr zu diesem Thema interessiert: [Gitlab websocket vs polling discussion](url)

@stg93 Wir interessiern uns auf jedenfall für dein Projekt. Wirst du hierzu den Code veröffentlichen? Die Implementierung am Raspberry ist sicher auch für andere Nutzer spannend. Wir können dein Projekt dann auch gerne hier verlinken!

Beste Grüße, Philip

**Comment by stg93** [comment]
Ok danke für deine Hilfe!

Ich kann den Code gerne auf GitHub stellen. Sobald ich fertig bin schicke ich dir den Link.

**Comment by pmig** [comment]
Ja perfekt. Viel Erfolg bei der Entwicklung.

**Comment by stg93** [comment]
Das fertige Projekt ist in diesem [Repository](https://github.com/stg93/blaulichtsms_einsatzmonitor_tv_controller).

**Comment by ulbrich** [comment]
Das Pollen ist für mich ebenfalls fein, aber könntet Ihr vielleicht einen Last-Modified Header mitschicken oder ein ETag? Am besten so, dass für das Pollen lediglich ein HEAD notwendig ist?

**Comment by pmig** [comment]
Ein ETag und eine eventuelle 304 Response (auch für HEAD) ist eine super Verbesserung. Ich habe nun ein seperates Issue dazu erstellt. (#8) Sobald die Änderung umgesetzt ist (Schätzungsweise Anfang Oktober), kommentiere ich das andere Issue.
