### ISSUE TITLE
Funktionen auslesen

### ISSUE THREAD

**Issue by DanielNe** [blaulichtSMS/docs#9]
Gibt es eine Möglichkeit die Funktionen über das API auszulesen?
Vielen Dank!
MfG
Daniel

**Comment by pmig** [comment]
Hallo Daniel,

Sry für die späte Antwort, wir haben nun auch die Funktionen über die API freigeschalten.

Ich füge sie gleich zu den docs hinzu.

Beste Grüße, Philip

**Comment by 19flashover69** [comment]
Hallo!
Leider erhalte ich beim auslesen der Funktion einen Fehler - Anscheinend kennt er die Variable nicht oder hab ich einen Denkfehler?!

```php
<?php
const DASHBOARD_BASE_URL = 'https://api.blaulichtsms.net/blaulicht/api/alarm/v1/dashboard/';
// FILL IN THE SESSION ID BELOW
const DASHBOARD_URL = DASHBOARD_BASE_URL . SESSION_ID;
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, DASHBOARD_URL);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$curlResponse = curl_exec($ch);
curl_close($ch);
$dashboardResult = json_decode($curlResponse);

foreach ($dashboardResult->alarms as $alarm) {
    echo("<b> <u>Alarm:</u> $alarm->alarmText </b><br>");
   
foreach ($alarm->recipients as $recipient) {
        echo("Name: $recipient->name <br> Status: $recipient->participation <br> Antwortnachricht: $recipient->functions <br><br>");

foreach ($alarm->functions as $functions) {
        echo("Name: $functions->name ");

    }
    echo("<hr>");
}}
?>
```

Gibt es auch eine Möglichkeit, die Rückmeldungen der Mitglieder zu sortieren? In Ja, Nein usw.

Lg

**Comment by pmig** [comment]
Hallo @19flashover69 

Die Funktionen hängen nicht direkt am Alarm, sondern wir liefern die Liste der Funktionen für jeden Teilnehmer mit aus. Folgender Code würde funktionieren:

```php
foreach ($alarm->recipients as $recipient) {
    echo("Name: $recipient->name <br> Status: $recipient->participation <br> Antwortnachricht: 
    $recipient->participationMessage <br><br>");
    foreach ($recipient->functions as $function) {
        echo("Funktion: $function->name ");
    }
    echo("<hr>");
}
```

Bzgl. der Sortieren, könntest du zum Beispiel die PHP Funktion [array_multisort](http://php.net/manual/en/function.array-multisort.php) verwenden.

Beste Grüße,
Philip

**Comment by 19flashover69** [comment]
Dankesehr :-)

Kann BlaulichtSMS eigentlich unterscheiden ob ein Einsatz bereits beendet wurde?

Lg
